### ISSUE TITLE
Does Deflect not support QT5?

### ISSUE THREAD

**Issue by lxq** [BlueBrain/Deflect#13]
My enviroments is win 8.1 + vs2013. When I use cmake to generate projects , it shows the following:
CMake Warning at d:/bin/cmake/share/cmake-3.0/Modules/FindQt4.cmake:616 (message):
  d:/libs/Qt/Qt5.4.1/5.4/msvc2013_64_opengl/bin/qmake.exe reported  QT_INSTALL_LIBS as "D:/libs/Qt/Qt5.4.1/5.4/msvc2013_64_opengl/lib" but  QtCore could not be found there.  Qt is NOT installed correctly for the  target build environment.

Does Deflect not support QT5?

**Comment by eile** [comment]
So far not. We might switch to Qt5 later this year.

**Comment by lxq** [comment]
thanks for your answer!
