### ISSUE TITLE
Read hosts from file

### ISSUE THREAD

**Issue by ghost** [BlueBrain/Deflect#151]
Instead of hardcoding the hosts that the application can connect to into the binary, it would be interesting if they got written to a file inside the Resources folder (I am thinking on the MacOS app).

This way, the file could be modified and there would not be a need to recompile the app.

We could even use your github releases to connect to our wall!

**Comment by eile** [comment]
We'll look into it.

Are you working with Madhu? Have you guys managed to get the touch working?

**Comment by ghost** [comment]
thanks

I am; no decent touch atm 😖

**Comment by eile** [comment]
You should try touch, it's awesome. ;)

**Comment by rdumusc** [comment]
implemented for the upcoming 0.13.0 release, just edit DesktopStreamer.app/Contents/Resources/defaults.json

**Comment by ghost** [comment]
awesome!

I'll download 0.13.0 as soon as it shows up

Thanks
