### ISSUE TITLE
building self-contained OSX app

### ISSUE THREAD

**Issue by ghost** [BlueBrain/Deflect#78]
I have tried to build a self contained OS X application but I'm not able. Any chance you could provide some basic instructions? Seeing your Travis or Jenkins builds would work too

Thanks
Noel

**Comment by rdumusc** [comment]
The deployment of the self contained app bundle should be automatic when you do a 'make install'.
It relies on the 'macdeployqt' command line tool, so make sure that it is in your PATH.

For reference, here is how our jenkins plan builds the app:

```
#!/bin/bash
export PATH=/path/to/Qt5.5.0/5.5/clang_64/bin:/opt/local/bin:/opt/local/sbin:$PATH

mkdir build
cd build

cmake .. \
  -GNinja \
  -DCMAKE_INSTALL_PREFIX=install/ \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_PREFIX_PATH=/path/to/Qt5.5.0

ninja all && ninja tests && ninja install
```

**Comment by ghost** [comment]
That helps, I wasn't using ninja

Thanks

**Comment by rdumusc** [comment]
Glad it helped!
(ninja isn't required though, it works just the same with make)
